---
driver:
  name: vagrant
  boot_timeout: 1200

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[heatlamp::default]
      # Integration tests for php applications
      - recipe[heatlamp::_integration]
    attributes:
      apt:
        # Force apt to update package cache at compile time
        compile_time_update: true
      mysql:
        server_root_password: rootpass
        server_debian_password: debpass
        server_repl_password: replpass
